model:
  state: "train"  # "train" or "eval"
  ch: 128
  ch_mult: [1, 2, 4, 4]
  n_res_blocks: 2
  attn: [2, 3]
  attn_heads: 1
  dropout: 0.15
  compile: False  # torch >= 2.0

diffusion:
  T: 1000
  beta_1: 0.0001
  beta_T: 0.02
  w_s: 0.5
  w_p: 0.5

data:
  train_pairs: 5000
  eval_pairs: 500
  ch: 3
  size: 64

path:
  train_dataset: "D:\\_Project\\Dataset\\AlphaPoseData\\train\\data" #"D:\\_Project\\Dataset\\In-shop Clothes Retrieval Benchmark"
  eval_dataset: "D:\\_Project\\Dataset\\AlphaPoseData\\test\\data"
  weight_dir: "Weigh"
  weight: "ckpt_0.pt"
  sample_dir: "Images"

train:
  pretrained: False
  epoch: 1000
  start_epoch: 0
  end_epoch: 10
  batch_size: 1

optim:
  lr: 0.0001
  weight_decay: 0.0001
  grad_clip: 1.0
  multiplier: 2.0

eval:
  batch_size: 1
